### PR TITLE
Different take on `main` highlighting `go install` and `go run` for ... servers/cli binaries

### PR DESCRIPTION
**Pull request by ldemailly**

### CODE REVIEW

**Comment by jrwren** [comment]
IMO that is anti-idiomatic. import paths should be optimized for importing to go code, not for installing via go install.

I could change my mind, but AFAICT, importable library at root is the idiomatic Go pattern, with main packages in subdirectories. I guess the real answer, like everything is, "it depends" and the important part is to not change package paths once they are published.

**Comment by ldemailly** [comment]
idioms evolve over time, it's same as `pkg/` (it was/is still used a lot)

It used to be, before go:embed and debug.BuildInfo that you couldn't "install" just using `go install` or run with just `go run <url>` but that's the past and I think it's important to socialize that

also I believe the text currently does reflect you can do _either_ vs original text which implies you must move your binary to cmd/execname ?

**Comment by egonelbre** [comment]
I would consider it idiomatic, e.g. see https://github.com/robpike/ivy

I.e. if your primary thing you are shipping is a single binary or tool, then it's nicer at root. If it's a library and the binaries are just a supplement, then have them else. If you have multiple primary binaries, then having a `cmd` is nice.

**Comment by jrwren** [comment]
That example is enough to convince me.

**Pull request merged**
